/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.UsuarioControlador;
import Modelo.ConsulU;
import Modelo.UsuarioPOO;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author HP
 */
public class MenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuGerente() {
        initComponents();
    }

    public JButton getBtnProductos() {
        return botUsuN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        botGestiones = new javax.swing.JButton();
        botUsuN = new javax.swing.JButton();
        botInformes = new javax.swing.JButton();
        botAyuda = new javax.swing.JButton();
        botAjustes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botInventario = new javax.swing.JButton();
        botPreCali = new javax.swing.JButton();
        botClientes = new javax.swing.JButton();
        botReportes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1162, 620));
        setResizable(false);
        setSize(new java.awt.Dimension(1162, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1162, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(1162, 620));
        jPanel1.setLayout(null);

        jPanel4.setLayout(null);

        botGestiones.setBackground(new java.awt.Color(90, 0, 0));
        botGestiones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botGestiones.setForeground(new java.awt.Color(255, 255, 255));
        botGestiones.setText("G E S T I O N E S");
        botGestiones.setBorder(null);
        botGestiones.setBorderPainted(false);
        botGestiones.setFocusPainted(false);
        botGestiones.setFocusable(false);
        botGestiones.setRequestFocusEnabled(false);
        botGestiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botGestionesActionPerformed(evt);
            }
        });
        jPanel4.add(botGestiones);
        botGestiones.setBounds(20, 180, 290, 50);

        botUsuN.setBackground(new java.awt.Color(90, 0, 0));
        botUsuN.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botUsuN.setForeground(new java.awt.Color(255, 255, 255));
        botUsuN.setText("USUARIO");
        botUsuN.setBorder(null);
        botUsuN.setBorderPainted(false);
        botUsuN.setFocusPainted(false);
        botUsuN.setFocusable(false);
        botUsuN.setRequestFocusEnabled(false);
        botUsuN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botUsuNActionPerformed(evt);
            }
        });
        jPanel4.add(botUsuN);
        botUsuN.setBounds(20, 250, 290, 50);

        botInformes.setBackground(new java.awt.Color(90, 0, 0));
        botInformes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botInformes.setForeground(new java.awt.Color(255, 255, 255));
        botInformes.setText("I N F O R M E S");
        botInformes.setBorder(null);
        botInformes.setBorderPainted(false);
        botInformes.setFocusPainted(false);
        botInformes.setFocusable(false);
        botInformes.setRequestFocusEnabled(false);
        jPanel4.add(botInformes);
        botInformes.setBounds(20, 320, 290, 50);

        botAyuda.setBackground(new java.awt.Color(90, 0, 0));
        botAyuda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botAyuda.setForeground(new java.awt.Color(255, 255, 255));
        botAyuda.setText("A Y U D A");
        botAyuda.setBorder(null);
        botAyuda.setBorderPainted(false);
        botAyuda.setFocusPainted(false);
        botAyuda.setFocusable(false);
        botAyuda.setRequestFocusEnabled(false);
        botAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAyudaActionPerformed(evt);
            }
        });
        jPanel4.add(botAyuda);
        botAyuda.setBounds(20, 390, 290, 50);

        botAjustes.setBackground(new java.awt.Color(90, 0, 0));
        botAjustes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botAjustes.setForeground(new java.awt.Color(255, 255, 255));
        botAjustes.setText("A J U S T E S");
        botAjustes.setBorder(null);
        botAjustes.setBorderPainted(false);
        botAjustes.setFocusPainted(false);
        botAjustes.setFocusable(false);
        botAjustes.setRequestFocusEnabled(false);
        jPanel4.add(botAjustes);
        botAjustes.setBounds(20, 460, 290, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background2.jpg"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(0, 0, 1162, 775);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(830, 0, 330, 620);

        jPanel2.setLayout(null);

        botInventario.setBackground(new java.awt.Color(90, 0, 0));
        botInventario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botInventario.setForeground(new java.awt.Color(255, 255, 255));
        botInventario.setText("I N V E N T A R I O");
        botInventario.setBorder(null);
        botInventario.setBorderPainted(false);
        botInventario.setFocusPainted(false);
        botInventario.setFocusable(false);
        botInventario.setRequestFocusEnabled(false);
        jPanel2.add(botInventario);
        botInventario.setBounds(20, 240, 290, 50);

        botPreCali.setBackground(new java.awt.Color(90, 0, 0));
        botPreCali.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botPreCali.setForeground(new java.awt.Color(255, 255, 255));
        botPreCali.setText("P R E - C A L I F I C A C I O N");
        botPreCali.setBorder(null);
        botPreCali.setBorderPainted(false);
        botPreCali.setFocusPainted(false);
        botPreCali.setFocusable(false);
        botPreCali.setRequestFocusEnabled(false);
        jPanel2.add(botPreCali);
        botPreCali.setBounds(20, 300, 290, 50);

        botClientes.setBackground(new java.awt.Color(90, 0, 0));
        botClientes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botClientes.setForeground(new java.awt.Color(255, 255, 255));
        botClientes.setText("C L I E N T E S");
        botClientes.setBorder(null);
        botClientes.setBorderPainted(false);
        botClientes.setFocusPainted(false);
        botClientes.setFocusable(false);
        botClientes.setRequestFocusEnabled(false);
        botClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botClientesActionPerformed(evt);
            }
        });
        jPanel2.add(botClientes);
        botClientes.setBounds(20, 360, 290, 50);

        botReportes.setBackground(new java.awt.Color(90, 0, 0));
        botReportes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botReportes.setForeground(new java.awt.Color(255, 255, 255));
        botReportes.setText("R E P O R T E S");
        botReportes.setBorder(null);
        botReportes.setBorderPainted(false);
        botReportes.setFocusPainted(false);
        botReportes.setFocusable(false);
        botReportes.setRequestFocusEnabled(false);
        jPanel2.add(botReportes);
        botReportes.setBounds(20, 420, 290, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SECCION GERENTE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 310, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 180, 80, 19);

        jlbUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jlbUsuario);
        jlbUsuario.setBounds(130, 170, 180, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background2.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 1162, 775);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 330, 620);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        botSalir.setBackground(new java.awt.Color(90, 0, 0));
        botSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botSalir.setForeground(new java.awt.Color(255, 255, 255));
        botSalir.setText("S A L I R");
        botSalir.setBorder(null);
        botSalir.setBorderPainted(false);
        botSalir.setFocusPainted(false);
        botSalir.setFocusable(false);
        botSalir.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(botSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(330, 540, 830, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo3.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 150, 460, 390);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("V E N T A S");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 20, 500, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1162, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botClientesActionPerformed

    private void botAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botAyudaActionPerformed

    private void botUsuNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botUsuNActionPerformed
        botUsuN.setBackground(Color.cyan);
        UsuarioPOO usuario = new UsuarioPOO();
        Usuario vista = new Usuario();
        ConsulU consulU = new ConsulU();
        UsuarioControlador controlador = new UsuarioControlador(usuario, vista, consulU);

        vista.setVisible(true);

    }//GEN-LAST:event_botUsuNActionPerformed

    private void botGestionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botGestionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botGestionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botAjustes;
    public javax.swing.JButton botAyuda;
    public javax.swing.JButton botClientes;
    public javax.swing.JButton botGestiones;
    public javax.swing.JButton botInformes;
    public javax.swing.JButton botInventario;
    public javax.swing.JButton botPreCali;
    public javax.swing.JButton botReportes;
    private javax.swing.JButton botSalir;
    public javax.swing.JButton botUsuN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbUsuario;
    // End of variables declaration//GEN-END:variables
}
